version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    docker:
      - image: openjdk:17
    executor: android/android-machine
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew
      - run:
          name: Create local.properties
          command: touch local.properties
      - run:
          name: Add BASE_URL to local.properties
          command: echo "BASE_URL=${BASE_URL}" >> local.properties
      - run:
          name: Add GITHUB_TOKEN to local.properties
          command: echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> local.properties
      - run:
          name: Add HOSTNAME to local.properties
          command: echo "HOSTNAME=${HOSTNAME}" >> local.properties
      - run:
          name: Add PASSPHRASE to local.properties
          command: echo "PASSPHRASE=${PASSPHRASE}" >> local.properties
      - run:
          name: Add CERTIFICATE PINNER 1 to local.properties
          command: echo "CERTIFICATE_PINNER_1=${CERTIFICATE_PINNER_1}" >> local.properties
      - run:
          name: Add CERTIFICATE PINNER 2 to local.properties
          command: echo "CERTIFICATE_PINNER_2=${CERTIFICATE_PINNER_2}" >> local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
