version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Create local.properties
          command: touch local.properties
      - run:
          name: Add BASE_URL to local.properties
          command: echo "BASE_URL=${BASE_URL}" >> local.properties
      - run:
          name: Add GITHUB_TOKEN to local.properties
          command: echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> local.properties
      - run:
          name: Add HOSTNAME to local.properties
          command: echo "HOSTNAME=${HOSTNAME}" >> local.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
